<article class="post">
    <header>
        <h1 class="entry-title">Hugo Award Categories</h1>
    </header>
    <div class="entry-content">
        <h2>The Official Rules</h2>
        <p>
            The official definition of the rules for the Hugo Awards can be found in Article 3 of the Constitution of the World Science Fiction Society. What follows is a plain English interpretation of those rules. In case of any ambiguity, the Constitution does, of course, take precedence.
        </p>
        <p>
            (Note: The WSFS Constitution usually changes annually, depending on what amendments are ratified at a given Worldcon. It can be quite a while sometimes for the revised version of the Constitution to be updated on wsfs.org. Each year’s Worldcon is required to distribute the current version of the Constitution to their members, and in particular a copy of the Hugo Award rules must be distributed with the Hugo Award ballot. If the version of the WSFS Constitution at the WSFS web site appears to be out of date, check with the current Worldcon to see if they have a more recent version. In general, WSFS.org, TheHugoAwards.org, and the current Worldcon’s web sites are run by different groups and their updates are not coordinated. This is due to the highly distributed nature of Worldcons. There is no true central organization of WSFS, and each Worldcon is operated by an independent group.)
        </p>
        <h2>Types of Award Category</h2>
        <p>
            There are three main types of Hugo Award category:
        </p>
        <ol>
            <li>Individual works, for example a single book or film, in which case the Award is given for that work;</li>
            <li>People, for example Best Professional Artist, in which case the Award is given for the work that person has done in the year of eligibility. Please note that “year of eligibility” qualification. If X happens to be the most famous SF artist in the world, but he has produced no work in the year of eligibility, then he should not be nominated.</li>
            <li>Serial publications, for example Best Fanzine, in which case the Award is given for the entire run of that publication in the year of eligibility, not for a single issue.</li>
        </ol>
    </div>
    <header>
        <h1 class="entry-title">The Voting System</h1>
    </header>
    <div class="entry-content">
        <p>[This article describes the current voting system. For an overview of how the current system evolved, see A Short History of the Hugo Awards Process elsewhere on this site. Also note that in case of any inconsistency between this document and the actual rules in the current version of the WSFS Constitution, the WSFS Constitution always takes precedence.]</p>
        <p>Many people find the Hugo voting system (called “Instant Runoff Voting“) very complicated. While the process is indeed involved, the basic idea is simple and the intention is laudable. Basically the idea is to make sure that the winner has majority support. In ordinary governmental elections it is possible for the winner to be someone that 40% of the people like and 60% of the people hate, because that 60% could not agree among themselves on a candidate. The Hugo voting system is designed to avoid results like that.</p>
        <h2>Nominations</h2>
        <p>Nominations are easy. Each person gets to nominate up to five entries in each category. You don’t have to use them all, but you have the right to five. Repeating a nomination in the same category will not affect the result; for instance, if you nominate the same story five times for Best Short Story, it will count as only a single nomination for that story. When all the nominations are in, the Hugo Administrator totals the votes for each work or person using the “E Pluribus Hugo” tallying system explained in more detail at the 2017 Worldcon’s Hugo Awards page under the heading “How are Hugo nominations going to be tallied?”</p>
        <p>The six works/people with the highest totals (including any ties for the final position; see below) go through to the final ballot and are considered “Hugo Award finalists.”</p>
        <p>(Note that you can nominate multiple works by the same person in the specific-work categories: For example, you can nominate two short stories by the same author in Best Short Story or two fanzines edited by the same person for Best Fanzine. Also, someone can be eligible in two different categories simultaneously; for example, you could nominate someone for Best Editor, Long Form and Best Fan Writer at the same time. What you can’t do is nominate the same short story more than once or nominate the same person for Best Editor, Short Form or Best Fan Artist more than once; the Administrator will ignore your extra votes in the same category. )</p>
        <p>The full details of the nominations are not released until after the final ballot. This is to prevent the nomination numbers influencing voters in the final ballot. Once the final ballot is over a list of the top 15 works/people, together with the number of nominations they received, will be published. Only those works/people appearing on the final ballot are considered “Hugo Award finalists.”</p>
        <p>Something that Worldcons often do before the final ballot is publish the number of nomination votes case and how many works/people were nominated overall as well as the total number of voters. A common mistake that people make is to forget that each voter gets up to six nominations in each category. For example, if a category has 30 nominees and 35 ballots that does not mean that most nominees only got one vote. There could have been up to 35 * 6 = 210 votes.</p>
        <h2>Ties</h2>
        <p>There is one situation in which more than six works/people can make it through to the final ballot. If there is a tie for for the final place on the shortlist, then all of the tied works/people will proceed to the final ballot. While this was moderately common prior to 2017, the current nominating system does make this situation unlikely.</p>
        <p>Prior to 2017, it was also possible for fewer works/people to make it through. There was a minimum requirement of three finalists, but if the lower-placing works/people received less than 5% of the total ballots cast then they did not make it onto the shortlist. Effective in 2017, this rule was repealed, and works/people can make the shortlist even if they get less than 5% of the total ballots cast in that category.</p>
        <h2>Declining nomination</h2>
        <p>As a courtesy, Worldcon Hugo Administrators always approach the successful nominees before announcing the final ballot. Sometimes people do withdraw, for all sorts of reasons. If a successful nominee does withdraw, the work/person with the next highest number of votes is elevated to the final ballot, and the withdrawn nomination is not considered a “Hugo Award finalist.”</p>
        <p>There is a view that an author who has more than one work on the final ballot should withdraw all but one in order to have a better chance of winning. This is a myth. One of the reasons for having a complicated voting system is to prevent things like that from happening. “Vote splitting” in a ranked-choice/instant-runoff/preferential voting system such as we use for the final ballot isn’t an issue, because even if if a given author’s works “split” the voters support, the finalist that is eliminated</p>
        <h2>How to vote in the final ballot</h2>
        <p>The final ballot is a bit more complicated. You get to rank each of the finalists in order of preference. Place a 1 against the work or person you most want to win, 2 against your second favorite and so on. Although you are not required to rank all of the finalists, the process works best if voters experience all of the works in a category. Recent Worldcons have expended great efforts to make it easier for voters to do this. If you can, we suggest that you do try all to read/watch/look at all of the finalists before voting. If you haven’t had the opportunity to experience all of the finalists, however, you are still eligible to vote. If you only rank the limited set you have experience of or wish to rank, your vote will be counted alongside all the others.</p>
        <h2>No Award</h2>
        <p>Under each category you will also be given the choice of voting for No Award.</p>
        <p>You should vote for No Award as your first choice if you believe that none of the finalists are worthy of the Award, or that the Award category should be abolished. If you vote for No Award in any other position it means that you believe the finalists you placed above No Award were worthy of a Hugo, but that those not placed above it were not worthy. However, as we shall see, it is possible to rank finalists below No Award and have an effect on the outcome.</p>
        <h2>The first round of counting</h2>
        <p>OK, time now to count the votes. Firstly, any invalid ballots are separated and removed. Note that votes for No Award are not invalid; they are treated just like an ordinary nomination. No Award can win; in which case no award will be given in the category that year. All of the valid votes, including those for No Award, are separated into piles depending on the first preference vote and counted. If, at this point, one finalist has more than 50% of the total valid ballots we have a potential winner. Otherwise, we need to eliminate someone.</p>
        <h2>Elimination and second round of counting</h2>
        <p>If there is no outright winner it is time to consider second preferences. All of the votes for the finalist with the lowest number of first preference votes are sorted again, this time by second preference. These are then counted, and the second preference totals for each finalist are added to the first preference totals. What is happening here is we are saying to the supporters of the least popular candidate, “OK, your candidate has lost, so out of the remaining candidates, who would you prefer to win?”</p>
        <p>Note that No Award is being treated just like other finalist. This means that No Award can be, and indeed normally is, eliminated as a candidate. Any preferences below No Award can then be redistributed just as they would be for any other candidate.</p>
        <p>The new totals for the remaining candidates are then checked. If one finalist has more than 50% of the total votes then we proceed to the No Award Test. Otherwise we continue counting.</p>
        <h2>And so on</h2>
        <p>The count continues as before with the least most popular finalist being eliminated and the votes for that finalist being redistributed amongst the survivors by third preference, fourth preference and so on. The process continues until one finalist has more than 50% of the total votes. By the time we reach the last two that must be true for one of them, unless there is a dead heat (which has happened, in which case both finalists get an award).</p>
        <h2>The No Award Test</h2>
        <p>The final check before a winner can be determined is known as the No Award Test. The valid ballots are divided into three piles: those in which No Award is ranked higher than the prospective winner (PW), those in which the prospective winner is ranked higher than No Award, and those in which neither No Award nor the prospective winner have preferences listed. Note that a ballot that contains a preference for the prospective winner but does not contain a preference for No Award goes into the “prospective winner higher than no award” pile. This is because lack of preference is, by definition, lower than any preference. Having got the three piles, the votes in the “prospective winner higher than No Award pile” and the votes in the “No Award higher than prospective winner” pile are counted. If the number of votes with the prospective winner placed higher is greater then the result is confirmed. If the pile with No Award placed higher is greater then no award is given in the category that year.</p>
        <p>It’s important that you realize that we count the ballot at this stage if the prospective winner is ranked OR No Award is ranked. You don’t have to rank them both. The only ballots that don’t count here are those that rank neither the PW nor NA. To put it another way:</p>
        <ul>
            <li>If the PW ranks higher than No Award (or the PW is ranked and NA isn’t mentioned), count this as a YES vote for the PW.</li>
            <li>If No Award ranks higher than the PW (or NA is ranked and the PW isn’t mentioned), count this as a NO vote against the PW.</li>
            <li>If neither the PW nor No Award is listed, this is a blank ballot and doesn’t count at all.</li>
        </ul>
        <p>Total the YES and NO votes. If YES wins, the PW is confirmed. If NO wins, then No Award wins.</p>
        <p>Important: If you rank No Award anywhere on your ballot and then leave any other choices blank, you have, in effect voted against all of the finalists you leave unranked. If, however, you leave works unranked and do not rank No Award at all, you have effectively abstained on the unranked works, voting neither for nor against them.</p>
        <h2>Lower placements</h2>
        <p>The method used by Hugo Administrators to determine placements after first place is to remove all of the rankings of the winner, and then repeat the counting process from the start. The winner of that second count will get second place. That finalist’s rankings are then removed, and the count repeated to find third place, and so on. If at any stage multiple finalists place, all of those finalists are eliminated for subsequent placements. For example, if one finalist places first, then two finalists tie for second place, then all three of the finalists who have placed thus far are eliminated before determining who placed fourth.</p>
        <p>As you can see, this leads to a lot of ballot counting. While you can do this by hand, it is cumbersome and time-consuming to do so. Some years ago, a fellow named Jeffrey Copeland wrote a computer program to automate this process, and most recent Hugo Award administrators have used this program to count the ballots and produce the mounds of statistics so beloved by Hugo watchers.</p>
    </div>
</article>